@org.junit.Test
public void divisionWorks() throws java.lang.Exception {
    fail();
    int result = calc.divide(6, 2);
    assertEquals(3, result);
}